# Excercise 1: Linear regression

Please write here your name and student id: Mariia Chernova 1908135

File bb.csv contains synthetic data about basketball player statistics. Columns Height, Years, Draftposition 
should be used to predict the value in column Pointsaverage. To do this the data should be read in, cleaned and scaled. Then a linear model that fits with the data is created. Last step is to predict the points average for Lauri Markkanen during his first years with Chicago Bulls. See https://en.wikipedia.org/wiki/Lauri_Markkanen for more information on Lauri.

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from numpy import genfromtxt

Read in the file "bb.csv" using numpy genfromtext() function.

In [58]:
bb_data = genfromtxt('bb.csv', delimiter=',', skip_header=1)
#raise NotImplementedError()

In [12]:
# Checking that data dimensions are correct.

assert(bb_data.shape[0] == 30)
assert(bb_data.shape[1] == 4)

Check that data makes sense by seeing if all values are non-negative etc. Remove any illegal (possibly corrupted) rows of data with numpy.delete(), for example. Assign cleaned data to variable bb_data_cleaned.

In [101]:
keep_row = (bb_data > 0).sum(1) == 4
bb_data_cleaned = bb_data[keep_row,]
# raise NotImplementedError()

In [102]:
assert(bb_data_cleaned.shape[0] == 28)
assert(bb_data_cleaned.shape[1] == 4)
assert(np.sum(bb_data_cleaned > 0) == 112)

Assign to variable x the features, to y the values we want to predict.

In [109]:
x = bb_data_cleaned[:,:3]
y = bb_data_cleaned[:,3]
#raise NotImplementedError()

In [110]:
assert(x.shape[0] == 28)
assert(x.shape[1] == 3)
assert(y.shape[0] == 28)

Scale x data with sklearn StandardScaler.

In [116]:
scaler = preprocessing.StandardScaler().fit(x)
scaled_x = scaler.transform(x)
scaled_x

array([[ 0.61085747, -1.37198868,  0.90657148],
       [-0.53578001, -0.30488637,  0.22359386],
       [-1.01354563, -0.0381108 , -1.14236137],
       [ 0.51530434, -1.1052131 , -0.11789495],
       [ 0.03753873,  0.49544036, -0.57321336],
       [ 0.99306996, -0.83843753, -0.23172455],
       [ 1.5663887 , -1.37198868,  1.5895491 ],
       [-2.25573623,  1.29576709, -1.25619098],
       [-0.63133313, -1.1052131 , -1.25619098],
       [ 0.3241981 ,  1.02899151,  0.10976426],
       [ 0.51530434, -0.57166195,  1.36188989],
       [ 1.37528245, -0.30488637, -1.37002058],
       [ 1.27972933,  0.76221593,  1.7033787 ],
       [-0.53578001,  1.29576709, -1.14236137],
       [-0.24912064,  2.3628694 , -0.57321336],
       [ 0.13309185, -1.37198868,  0.33742347],
       [-1.58686437, -0.0381108 , -0.23172455],
       [-0.72688626, -0.57166195,  0.10976426],
       [-1.20465187,  0.49544036, -0.23172455],
       [-0.72688626, -0.83843753, -1.37002058],
       [-1.20465187,  0.76221593,  1.931

In [124]:
scaler = preprocessing.StandardScaler().fit(x)
scaled_x = scaler.transform(x)
# raise NotImplementedError()

In [125]:
eps = 0.0001
assert(np.sum(scaled_x.mean(axis=0)) < eps)
assert(np.sum(scaled_x.std(axis=0)) < 3 + eps)

Split the data into training (x_train, y_train) and test (x_test, y_test) sets with the test set size 30% of all data.

In [126]:
np.random.seed(42) # Please do not remove
x_train, x_test, y_train, y_test = train_test_split(scaled_x, y, test_size=0.3)
# raise NotImplementedError()

In [127]:
assert(x_train.shape[0] == 19 and x_test.shape[0] == 9)
assert(y_train.shape[0] == 19 and y_test.shape[0] == 9)
assert(x_train.shape[1] == 3 and x_test.shape[1] == 3)

Create a linear model.

Assign the R^2 score of the model computed with test set to variable r2test.

In [132]:
model = linear_model.LinearRegression()
model.fit(x_train, y_train)
r2test = model.score(x_test, y_test)
# raise NotImplementedError()

In [133]:
assert(r2test - 0.8161738892 < eps)

Predict Lauri Markkanen's point average for seasons 17-18 and 18-19 using your model. Assign your predictions to variables lauri1718 and lauri1819.

In [158]:
lauri = np.array([[213,0,7],[213,1,7]])
lauri
# raise NotImplementedError()

array([[213,   0,   7],
       [213,   1,   7]])

In [159]:
scaled_lauri= scaler.transform(lauri)
scaled_lauri

array([[ 0.70641059, -1.63876426, -0.68704296],
       [ 0.70641059, -1.37198868, -0.68704296]])

In [162]:
predictions_lauri= model.predict(scaled_lauri)
print(predictions_lauri)

[19.78996207 20.76399068]


In [165]:
lauri1718=predictions_lauri[0]
lauri1819=predictions_lauri[1]

20.763990681161317

In [166]:
assert(lauri1718 - 19.78996201 < eps)
assert(lauri1819 - 20.76399068 < eps)