### Exercise 4: NMIST classification

Name and student id: Mariia Chernova 1908135

In [1]:
import numpy as np
from numpy import genfromtxt
import matplotlib.pyplot as plt
from sklearn.utils.extmath import cartesian
from sklearn.datasets import fetch_openml
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

In [2]:
x, y = fetch_openml('mnist_784', version=1, return_X_y=True) # download takes a while 

Standardize feature data and split the data into training and test sets with 30% for training.

In [27]:
scaler = preprocessing.StandardScaler().fit(x)
scaled_x = scaler.transform(x)
x_train, x_test, y_train, y_test = train_test_split(scaled_x, y, test_size=0.3)
# raise NotImplementedError()
print(x_train.shape)

(49000, 784)


In [29]:
assert(x_train.shape == (49000, 784))

Train a decision tree classifier model (assign to variable model) with default parameters. Compute training and test scores and assign them to training_score and test_score. Also print the confusion matrix for both training and test sets.

In [32]:
model = tree.DecisionTreeClassifier()
model.fit(x_train, y_train)
training_score = model.score(x_train, y_train)
test_score = model.score(x_test, y_test)
print("training accuracy", training_score)
print(confusion_matrix(model.predict(x_train), y_train))

print("validation accuracy", test_score)
cfm = confusion_matrix(model.predict(x_test), y_test)
print(cfm)
   
# raise NotImplementedError()

training accuracy 1.0
[[4849    0    0    0    0    0    0    0    0    0]
 [   0 5503    0    0    0    0    0    0    0    0]
 [   0    0 4869    0    0    0    0    0    0    0]
 [   0    0    0 4969    0    0    0    0    0    0]
 [   0    0    0    0 4795    0    0    0    0    0]
 [   0    0    0    0    0 4333    0    0    0    0]
 [   0    0    0    0    0    0 4776    0    0    0]
 [   0    0    0    0    0    0    0 5175    0    0]
 [   0    0    0    0    0    0    0    0 4813    0]
 [   0    0    0    0    0    0    0    0    0 4918]]
validation accuracy 0.8672380952380953
[[1881    2   24   20   18   37   25   12   19   10]
 [   2 2272   30   23   18   14    7   20   32    8]
 [  24   21 1797   62   25   27   25   41   45   18]
 [  18   15   65 1788   12   79    7   30   68   44]
 [  14   10   36   18 1727   26   37   25   40   92]
 [  26   10   14   94   22 1604   43    9   80   42]
 [  39    6   35   14   26   69 1900    3   31   10]
 [   4    7   53   31   25   20    2 

In [34]:
np.testing.assert_almost_equal(training_score, 1.0, decimal=1)
np.testing.assert_almost_equal(test_score, 0.87, decimal=1)

How many times in validation set
- digit 3 gets misclassified?
- digit 4 gets misclassified as 7?

What is the most misclassified digit?

Please answer in cell below.

YOUR ANSWER HERE

In [35]:
# digit 3 gets misclassified?
digit3_misclassified = cfm[:,3].sum()-cfm[3,3]
digit3_misclassified

384

In [36]:
# digit 4 gets misclassified as 7?
digit4_misclassified_as7 = cfm[7,4]
digit4_misclassified_as7

25

In [39]:
# What is the most misclassified digit?
digit_most_misclassified = np.argmax([cfm[:,i].sum()-cfm[i,i] for i in range(10)])
digit_most_misclassified

8

Train a random forest classifier model (assigned to variable model) with default parameters. Compute training and test scores and assign them to training_score and test_score. Also print the confusion matrix for both training and test sets.

In [40]:
model = RandomForestClassifier()
model.fit(x_train, y_train)
training_score = model.score(x_train, y_train)
test_score = model.score(x_test, y_test)

print("training accuracy", training_score)
print(confusion_matrix(model.predict(x_train), y_train))

print("validation accuracy", test_score)
print(confusion_matrix(model.predict(x_test), y_test))

# raise NotImplementedError()

/Users/maria/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


training accuracy 0.9992448979591837
[[4849    0    0    0    0    0    1    0    0    0]
 [   0 5503    0    0    0    0    2    0    0    0]
 [   0    0 4867    6    0    1    0    2    0    0]
 [   0    0    2 4961    0    2    0    0    0    2]
 [   0    0    0    0 4793    1    0    0    0    2]
 [   0    0    0    0    0 4328    2    0    0    2]
 [   0    0    0    0    0    0 4771    0    0    0]
 [   0    0    0    0    0    0    0 5171    0    3]
 [   0    0    0    1    0    0    0    0 4811    0]
 [   0    0    0    1    2    1    0    2    2 4909]]
validation accuracy 0.9444285714285714
[[2017    0    8    7    4   20   17    5    5    8]
 [   1 2338   12   11    5    5    5   15   11    7]
 [   5   15 2012   44   12   10    6   31   33   13]
 [   1    7   16 2007    3   52    2    4   31   16]
 [   6    4   15    5 1932   10   10   16   16   56]
 [   5    2    3   43    4 1818   34    2   32   16]
 [   8    4   10    4   12   21 2015    0   19    1]
 [   0    2   22   12 

In [41]:
np.testing.assert_almost_equal(training_score, 0.999, decimal=2)
np.testing.assert_almost_equal(test_score, 0.944, decimal=2)